version: '3.4'

services:
  frontend:
    image: ziadmmh/bigoven-frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  backend:
    image: ziadmmh/bigoven-backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
        - 5007:80
  reverseproxy:
    image: ziadmmh/bigoven-reverseproxy
    build:
      context: .
      dockerfile: reverseproxy/Dockerfile
    ports:
        - 80:80
  db:
    image: postgres
    volumes:
      - ./Backend/Data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"