//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Orm.HelperClasses
{
	/// <summary>Field Creation Class for entity CategoryEntity</summary>
	public partial class CategoryFields
	{
		/// <summary>Creates a new CategoryEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Id); }}
		/// <summary>Creates a new CategoryEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.IsActive); }}
		/// <summary>Creates a new CategoryEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity IngredientEntity</summary>
	public partial class IngredientFields
	{
		/// <summary>Creates a new IngredientEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(IngredientFieldIndex.Id); }}
		/// <summary>Creates a new IngredientEntity.Ingredient field instance</summary>
		public static EntityField2 Ingredient { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(IngredientFieldIndex.Ingredient); }}
		/// <summary>Creates a new IngredientEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(IngredientFieldIndex.IsActive); }}
		/// <summary>Creates a new IngredientEntity.RecipeId field instance</summary>
		public static EntityField2 RecipeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(IngredientFieldIndex.RecipeId); }}
	}

	/// <summary>Field Creation Class for entity InstructionEntity</summary>
	public partial class InstructionFields
	{
		/// <summary>Creates a new InstructionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(InstructionFieldIndex.Id); }}
		/// <summary>Creates a new InstructionEntity.Instruction field instance</summary>
		public static EntityField2 Instruction { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(InstructionFieldIndex.Instruction); }}
		/// <summary>Creates a new InstructionEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(InstructionFieldIndex.IsActive); }}
		/// <summary>Creates a new InstructionEntity.RecipeId field instance</summary>
		public static EntityField2 RecipeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(InstructionFieldIndex.RecipeId); }}
	}

	/// <summary>Field Creation Class for entity RecipeEntity</summary>
	public partial class RecipeFields
	{
		/// <summary>Creates a new RecipeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeFieldIndex.Id); }}
		/// <summary>Creates a new RecipeEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeFieldIndex.IsActive); }}
		/// <summary>Creates a new RecipeEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeFieldIndex.Title); }}
	}

	/// <summary>Field Creation Class for entity RecipesCategoryEntity</summary>
	public partial class RecipesCategoryFields
	{
		/// <summary>Creates a new RecipesCategoryEntity.CategoryId field instance</summary>
		public static EntityField2 CategoryId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipesCategoryFieldIndex.CategoryId); }}
		/// <summary>Creates a new RecipesCategoryEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipesCategoryFieldIndex.Id); }}
		/// <summary>Creates a new RecipesCategoryEntity.RecipeId field instance</summary>
		public static EntityField2 RecipeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipesCategoryFieldIndex.RecipeId); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Id); }}
		/// <summary>Creates a new UserEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.IsActive); }}
		/// <summary>Creates a new UserEntity.PasswordHash field instance</summary>
		public static EntityField2 PasswordHash { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.PasswordHash); }}
		/// <summary>Creates a new UserEntity.RefreshToken field instance</summary>
		public static EntityField2 RefreshToken { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.RefreshToken); }}
		/// <summary>Creates a new UserEntity.TokenCreated field instance</summary>
		public static EntityField2 TokenCreated { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.TokenCreated); }}
		/// <summary>Creates a new UserEntity.TokenExpires field instance</summary>
		public static EntityField2 TokenExpires { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.TokenExpires); }}
		/// <summary>Creates a new UserEntity.Username field instance</summary>
		public static EntityField2 Username { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Username); }}
	}
	

}