//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using Orm.FactoryClasses;
using Orm.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Orm.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitCategoryEntityInfo();
			InitIngredientEntityInfo();
			InitInstructionEntityInfo();
			InitRecipeEntityInfo();
			InitRecipesCategoryEntityInfo();
			InitUserEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits CategoryEntity's info objects</summary>
		private void InitCategoryEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CategoryFieldIndex), "CategoryEntity");
			this.AddElementFieldInfo("CategoryEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)CategoryFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)CategoryFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "Name", typeof(System.String), false, false, false, false,  (int)CategoryFieldIndex.Name, 1073741824, 0, 0);
		}

		/// <summary>Inits IngredientEntity's info objects</summary>
		private void InitIngredientEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(IngredientFieldIndex), "IngredientEntity");
			this.AddElementFieldInfo("IngredientEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)IngredientFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("IngredientEntity", "Ingredient", typeof(System.String), false, false, false, false,  (int)IngredientFieldIndex.Ingredient, 1000, 0, 0);
			this.AddElementFieldInfo("IngredientEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)IngredientFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("IngredientEntity", "RecipeId", typeof(System.Guid), false, true, false, false,  (int)IngredientFieldIndex.RecipeId, 0, 0, 0);
		}

		/// <summary>Inits InstructionEntity's info objects</summary>
		private void InitInstructionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(InstructionFieldIndex), "InstructionEntity");
			this.AddElementFieldInfo("InstructionEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)InstructionFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("InstructionEntity", "Instruction", typeof(System.String), false, false, false, false,  (int)InstructionFieldIndex.Instruction, 1000, 0, 0);
			this.AddElementFieldInfo("InstructionEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)InstructionFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("InstructionEntity", "RecipeId", typeof(System.Guid), false, true, false, false,  (int)InstructionFieldIndex.RecipeId, 0, 0, 0);
		}

		/// <summary>Inits RecipeEntity's info objects</summary>
		private void InitRecipeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RecipeFieldIndex), "RecipeEntity");
			this.AddElementFieldInfo("RecipeEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)RecipeFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("RecipeEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)RecipeFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("RecipeEntity", "Title", typeof(System.String), false, false, false, false,  (int)RecipeFieldIndex.Title, 1073741824, 0, 0);
		}

		/// <summary>Inits RecipesCategoryEntity's info objects</summary>
		private void InitRecipesCategoryEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RecipesCategoryFieldIndex), "RecipesCategoryEntity");
			this.AddElementFieldInfo("RecipesCategoryEntity", "CategoryId", typeof(System.Guid), false, true, false, false,  (int)RecipesCategoryFieldIndex.CategoryId, 0, 0, 0);
			this.AddElementFieldInfo("RecipesCategoryEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)RecipesCategoryFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("RecipesCategoryEntity", "RecipeId", typeof(System.Guid), false, true, false, false,  (int)RecipesCategoryFieldIndex.RecipeId, 0, 0, 0);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)UserFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)UserFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PasswordHash", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.PasswordHash, 1073741824, 0, 0);
			this.AddElementFieldInfo("UserEntity", "RefreshToken", typeof(System.String), false, false, false, true,  (int)UserFieldIndex.RefreshToken, 1073741824, 0, 0);
			this.AddElementFieldInfo("UserEntity", "TokenCreated", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.TokenCreated, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "TokenExpires", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.TokenExpires, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Username", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Username, 1073741824, 0, 0);
		}
	}
}