//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Orm.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitCategoryEntityMappings();
			InitIngredientEntityMappings();
			InitInstructionEntityMappings();
			InitRecipeEntityMappings();
			InitRecipesCategoryEntityMappings();
			InitUserEntityMappings();
		}

		/// <summary>Inits CategoryEntity's mappings</summary>
		private void InitCategoryEntityMappings()
		{
			this.AddElementMapping("CategoryEntity", @"postgres", @"public", "categories", 3, 0);
			this.AddElementFieldMapping("CategoryEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("CategoryEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
			this.AddElementFieldMapping("CategoryEntity", "Name", "name", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits IngredientEntity's mappings</summary>
		private void InitIngredientEntityMappings()
		{
			this.AddElementMapping("IngredientEntity", @"postgres", @"public", "ingredients", 4, 0);
			this.AddElementFieldMapping("IngredientEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("IngredientEntity", "Ingredient", "ingredient", false, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("IngredientEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 2);
			this.AddElementFieldMapping("IngredientEntity", "RecipeId", "recipe_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
		}

		/// <summary>Inits InstructionEntity's mappings</summary>
		private void InitInstructionEntityMappings()
		{
			this.AddElementMapping("InstructionEntity", @"postgres", @"public", "instructions", 4, 0);
			this.AddElementFieldMapping("InstructionEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("InstructionEntity", "Instruction", "instruction", false, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("InstructionEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 2);
			this.AddElementFieldMapping("InstructionEntity", "RecipeId", "recipe_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
		}

		/// <summary>Inits RecipeEntity's mappings</summary>
		private void InitRecipeEntityMappings()
		{
			this.AddElementMapping("RecipeEntity", @"postgres", @"public", "recipe", 3, 0);
			this.AddElementFieldMapping("RecipeEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("RecipeEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
			this.AddElementFieldMapping("RecipeEntity", "Title", "title", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits RecipesCategoryEntity's mappings</summary>
		private void InitRecipesCategoryEntityMappings()
		{
			this.AddElementMapping("RecipesCategoryEntity", @"postgres", @"public", "recipes_categories", 3, 0);
			this.AddElementFieldMapping("RecipesCategoryEntity", "CategoryId", "category_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("RecipesCategoryEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("RecipesCategoryEntity", "RecipeId", "recipe_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"postgres", @"public", "users", 7, 0);
			this.AddElementFieldMapping("UserEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("UserEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
			this.AddElementFieldMapping("UserEntity", "PasswordHash", "password_hash", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("UserEntity", "RefreshToken", "refresh_token", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("UserEntity", "TokenCreated", "token_created", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 4);
			this.AddElementFieldMapping("UserEntity", "TokenExpires", "token_expires", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 5);
			this.AddElementFieldMapping("UserEntity", "Username", "username", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 6);
		}

	}
}
