//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Orm.HelperClasses;
using Orm.FactoryClasses;
using Orm.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Orm.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'RecipesCategory'.<br/><br/></summary>
	[Serializable]
	public partial class RecipesCategoryEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private CategoryEntity _category;
		private RecipeEntity _recipe;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static RecipesCategoryEntityStaticMetaData _staticMetaData = new RecipesCategoryEntityStaticMetaData();
		private static RecipesCategoryRelations _relationsFactory = new RecipesCategoryRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Category</summary>
			public static readonly string Category = "Category";
			/// <summary>Member name Recipe</summary>
			public static readonly string Recipe = "Recipe";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class RecipesCategoryEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public RecipesCategoryEntityStaticMetaData()
			{
				SetEntityCoreInfo("RecipesCategoryEntity", InheritanceHierarchyType.None, false, (int)Orm.EntityType.RecipesCategoryEntity, typeof(RecipesCategoryEntity), typeof(RecipesCategoryEntityFactory), false);
				AddNavigatorMetaData<RecipesCategoryEntity, CategoryEntity>("Category", "RecipesCategories", (a, b) => a._category = b, a => a._category, (a, b) => a.Category = b, Orm.RelationClasses.StaticRecipesCategoryRelations.CategoryEntityUsingCategoryIdStatic, ()=>new RecipesCategoryRelations().CategoryEntityUsingCategoryId, null, new int[] { (int)RecipesCategoryFieldIndex.CategoryId }, null, true, (int)Orm.EntityType.CategoryEntity);
				AddNavigatorMetaData<RecipesCategoryEntity, RecipeEntity>("Recipe", "RecipesCategories", (a, b) => a._recipe = b, a => a._recipe, (a, b) => a.Recipe = b, Orm.RelationClasses.StaticRecipesCategoryRelations.RecipeEntityUsingRecipeIdStatic, ()=>new RecipesCategoryRelations().RecipeEntityUsingRecipeId, null, new int[] { (int)RecipesCategoryFieldIndex.RecipeId }, null, true, (int)Orm.EntityType.RecipeEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static RecipesCategoryEntity()
		{
		}

		/// <summary> CTor</summary>
		public RecipesCategoryEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public RecipesCategoryEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this RecipesCategoryEntity</param>
		public RecipesCategoryEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for RecipesCategory which data should be fetched into this RecipesCategory object</param>
		public RecipesCategoryEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for RecipesCategory which data should be fetched into this RecipesCategory object</param>
		/// <param name="validator">The custom validator object for this RecipesCategoryEntity</param>
		public RecipesCategoryEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected RecipesCategoryEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Category' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCategory() { return CreateRelationInfoForNavigator("Category"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Recipe' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoRecipe() { return CreateRelationInfoForNavigator("Recipe"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this RecipesCategoryEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static RecipesCategoryRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Category' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCategory { get { return _staticMetaData.GetPrefetchPathElement("Category", CommonEntityBase.CreateEntityCollection<CategoryEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Recipe' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathRecipe { get { return _staticMetaData.GetPrefetchPathElement("Recipe", CommonEntityBase.CreateEntityCollection<RecipeEntity>()); } }

		/// <summary>The CategoryId property of the Entity RecipesCategory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "recipes_categories"."category_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid CategoryId
		{
			get { return (System.Guid)GetValue((int)RecipesCategoryFieldIndex.CategoryId, true); }
			set	{ SetValue((int)RecipesCategoryFieldIndex.CategoryId, value); }
		}

		/// <summary>The Id property of the Entity RecipesCategory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "recipes_categories"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)RecipesCategoryFieldIndex.Id, true); }
			set	{ SetValue((int)RecipesCategoryFieldIndex.Id, value); }
		}

		/// <summary>The RecipeId property of the Entity RecipesCategory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "recipes_categories"."recipe_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid RecipeId
		{
			get { return (System.Guid)GetValue((int)RecipesCategoryFieldIndex.RecipeId, true); }
			set	{ SetValue((int)RecipesCategoryFieldIndex.RecipeId, value); }
		}

		/// <summary>Gets / sets related entity of type 'CategoryEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CategoryEntity Category
		{
			get { return _category; }
			set { SetSingleRelatedEntityNavigator(value, "Category"); }
		}

		/// <summary>Gets / sets related entity of type 'RecipeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual RecipeEntity Recipe
		{
			get { return _recipe; }
			set { SetSingleRelatedEntityNavigator(value, "Recipe"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Orm
{
	public enum RecipesCategoryFieldIndex
	{
		///<summary>CategoryId. </summary>
		CategoryId,
		///<summary>Id. </summary>
		Id,
		///<summary>RecipeId. </summary>
		RecipeId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Orm.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: RecipesCategory. </summary>
	public partial class RecipesCategoryRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between RecipesCategoryEntity and CategoryEntity over the m:1 relation they have, using the relation between the fields: RecipesCategory.CategoryId - Category.Id</summary>
		public virtual IEntityRelation CategoryEntityUsingCategoryId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Category", false, new[] { CategoryFields.Id, RecipesCategoryFields.CategoryId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between RecipesCategoryEntity and RecipeEntity over the m:1 relation they have, using the relation between the fields: RecipesCategory.RecipeId - Recipe.Id</summary>
		public virtual IEntityRelation RecipeEntityUsingRecipeId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Recipe", false, new[] { RecipeFields.Id, RecipesCategoryFields.RecipeId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticRecipesCategoryRelations
	{
		internal static readonly IEntityRelation CategoryEntityUsingCategoryIdStatic = new RecipesCategoryRelations().CategoryEntityUsingCategoryId;
		internal static readonly IEntityRelation RecipeEntityUsingRecipeIdStatic = new RecipesCategoryRelations().RecipeEntityUsingRecipeId;

		/// <summary>CTor</summary>
		static StaticRecipesCategoryRelations() { }
	}
}
